Refactored how a cell displays when using ignore functionality
unclebob/fitnesse pull request #1429
Opened 2023-03-31 09:22 UTC by eireglas

Now it will show the original value along with 'Test Not Run'.

See below original issue where 'Test not run' overwrite original value:
![image](https://user-images.githubusercontent.com/20017348/229079673-b9123177-be72-48d1-ad46-9022d61d32ba.png)

Now with this code change it will show the original value also:
![image](https://user-images.githubusercontent.com/20017348/229079912-7541fae0-defb-4eda-9321-42299b2cc4fb.png)

2023-03-31 10:19 UTC, eireglas commented
@fhoeben If you could review, that would be great!

2023-03-31 18:17 UTC, fhoeben commented on src/fitnesse/testsystems/slim/HtmlTable.java
> +            if(testResult.getMessage() != null){
```suggestion
            if (testResult.getMessage() != null) {
```

2023-03-31 18:17 UTC, fhoeben requested changes
Looks good to me

2023-04-01 18:10 UTC, nguyentuanviet77 commented
I didn't agree with this change. Actually, if it was shown the value "Hello" then it was running the Echo function already but the result check was not run and it was inconsistent. I think shouldn't change anything and keep it current for now

2023-04-01 18:30 UTC, eireglas commented
I disagree with the last comment. I don't see why we can't have the original value shown when we are ignoring the test.

2023-04-02 13:25 UTC, fhoeben commented
@nguyentuanviet77 I don't believe the `Hello` shown in this case is the return value from the echo method, but the expected value as was present in the table before the test was run. 

But this confusion is likely to occur with this change.

@eireglas can you elaborate why it is good/important to show the expected value even when the test is aborted and the lines are not actually run?

Thinking about it now I believe one could even argue that all rows after the exception should not be shown and only a single one (spanning the whole table) instead showing 'Test aborted' (or a similar text).

2023-04-02 18:24 UTC, nguyentuanviet77 commented
@fhoeben. 

> @nguyentuanviet77 I don't believe the `Hello` shown in this case is the return value from the echo method, but the expected value as was present in the table before the test was run.
> 
> But this confusion is likely to occur with this change.
> 
Yes, agreed, I didn't read the code change yet, but let's imagine that when the step was ignored but still shown the result in the table content was not make sense

@eireglas as you can see the original value was still shown in the table content as the parameters why did you need to show it again? let's imagine that if this was not the **echo** method it was your code method. What should behave with more than one parameter? what was the benefit to show the original param values here?

2023-04-02 19:16 UTC, eireglas commented
@fhoeben @nguyentuanviet77  Apologies, I probably explained it incorrectly when I said "Now it will show the original value along with 'Test Not Run'.". When I say original value here I mean the original cell value before it was populated with 'Test not run' which actually is the expected value. The reason I suggested this change is purely for readability. Nothing else. So if a test is ignored we can still see what the expected value was. If this small change is to confusing I've no problem cancelling this change.

2023-04-20 11:10 UTC, closed without merging