Add Variable values to ScopeVariablesResponder
unclebob/fitnesse pull request #1472
Opened 2024-01-12 10:41 UTC by AlexNetcare

This will add the values for the variables to the table. So instead of going to a variables location you can see the value directly in the table.

2024-01-12 17:00 UTC, fhoeben commented
Can you add a description of this feature to `FitNesseRoot/FitNesse/ReleaseNotes/content.txt`

Furthermore I just noticed that the responder is not documented at all in the user guide. That is a shame as it is a really useful tool. Could you maybe add a short description somewhere in the user guide pages (I think `FitNesseRoot/FitNesse/UserGuide/WritingAcceptanceTests/VariableScope/content.txt` might be a good location)? 
Doesn't have to be fancy, but it would be good if people could see they can get an overview (and how).

2024-01-15 11:44 UTC, AlexNetcare commented
There is a small information in the User Guide for the Responder under `FitNesseRoot/FitNesse/UserGuide/AdministeringFitNesse/RestfulServices/content.txt`. But updating the user guide for the VariableScope still seems good to me.

Additionally on the Variable Scope page, I added the information that only variables with !define are shown on the page. Variables like PAGE_PATH or PAGE_NAME are not shown. I am not sure if that was intended or not but I didn't want to change too much.

2024-01-15 16:47 UTC, fhoeben requested changes
Minor rephrase of some of the documentation, but great otherwise

2024-01-15 16:47 UTC, fhoeben commented on FitNesseRoot/FitNesse/UserGuide/WritingAcceptanceTests/VariableScope/content.txt
> +All variables that have been declared using !define can be checked by adding ?variables at the end. For example .FitNesse.UserGuide.FitNesseWiki?variables will show a table with the names, their valu
```suggestion
All variables that have been declared using !style_code(!define) can be checked by adding !style_code(?variables) at the end of the page's url.
For example !style_code(!-http://myFitNesseHost/FitNesse.UserGuide.FitNesseWiki?variables-!) will show a table with the names, their values and the pages the values are defined.
```

2024-01-15 16:47 UTC, fhoeben commented on FitNesseRoot/FitNesse/ReleaseNotes/content.txt
> + * Added the values to the variables page. ([[1472][https://github.com/unclebob/fitnesse/pull/1472]])
```suggestion
 * Added the defined values to the overview of all variables in scope. ([[1472][https://github.com/unclebob/fitnesse/pull/1472]])
```

2024-01-16 17:42 UTC, merged