Fix RerunLastFailures problem. Appear the perfix only one time
unclebob/fitnesse pull request #1512
Opened 2024-06-06 11:54 UTC by Eqerem-Hena

Fix the #1342 issue.

2024-06-06 12:21 UTC, fhoeben commented
@Eqerem-Hena Thanks a lot for your PR!

I believe you are generating unique names for each re-rerun by adding a counter at the end, correct?
To me this seems overkill as it keeps making a lot of pages if the rerun is retried often.

Like I stated in the issue just having one rerun per page/suite seems fine. So this PR could be much simpler: just don't add the `RerunLastFailures_` prefix if the  full page name already starts with that.
Do you think that is too limited?

2024-06-06 12:23 UTC, fhoeben commented
It also seems like some of the existing tests failed, can that be related to your change or did we let something else slip through and break that already?

2024-06-06 21:49 UTC, Eqerem-Hena commented
> @Eqerem-Hena Thanks a lot for your PR!
> 
> I believe you are generating unique names for each re-rerun by adding a counter at the end, correct? To me this seems overkill as it keeps making a lot of pages if the rerun is retried often.
> 
> Like I stated in the issue just having one rerun per page/suite seems fine. So this PR could be much simpler: just don't add the `RerunLastFailures_` prefix if the full page name already starts with that. Do you think that is too limited?

I think it is a better idea to add the counter at the end, as in this way it will be more understandable to the user which rerun page is.

2024-06-06 21:51 UTC, Eqerem-Hena commented
> It also seems like some of the existing tests failed, can that be related to your change or did we let something else slip through and break that already?

I don't think so. It's probably from a previous commit.

2024-06-07 08:24 UTC, fhoeben commented
The original submitter of the issue indicated:
> This would help keep my FitNesseRoot directory from exploding...

So they prefer not to have an additional file for each rerun.

2024-06-07 20:40 UTC, Eqerem-Hena commented
> The original submitter of the issue indicated:
> 
> > This would help keep my FitNesseRoot directory from exploding...
> 
> So they prefer not to have an additional file for each rerun.

I did a new commit. Please, check it out!

2024-06-16 08:30 UTC, fhoeben requested changes
Looks really good. Thank you. Some minor comments and then we can merge

2024-06-16 08:30 UTC, fhoeben commented on src/fitnesse/responders/run/SuiteResponder.java
> +      String newFullPathName = fullPathName.replace(".", "-");
I think it makes more sense to to the replace on line 297 to remove the duplicated code from both branches

2024-06-16 08:30 UTC, fhoeben commented on test/fitnesse/responders/run/SuiteResponderTest.java
> +    assertEquals("RerunLastFailures_SomePage".replace(".", "-"), result);
```suggestion
    assertEquals("RerunLastFailures_SomePage", result);
```

2024-06-16 08:30 UTC, fhoeben commented on test/fitnesse/responders/run/SuiteResponderTest.java
> +    assertEquals("RerunLastFailures_SomeOtherPage".replace(".", "-"), result);
```suggestion
    assertEquals("RerunLastFailures_SomeOtherPage", result);
```

2024-06-16 08:30 UTC, fhoeben commented on test/fitnesse/responders/run/SuiteResponderTest.java
> +
It is a good idea to add the replacement of `.` by `-` in that page names, but I would like to see that in separate test cases where the `fullPathName` actually contains a period and then also just do an `assertEquals` where the expect value is a literal with the periods replaced.

In the current setup the `replace` in the assertion doesn't do anything and the test doesn't make explicit what it is expecting

2024-06-16 18:24 UTC, fhoeben commented
Could you also update the release notes?

2024-07-07 09:37 UTC, fhoeben commented
Cleaned up the tests in #1519

2024-07-07 09:37 UTC, closed without merging